### ISSUE TITLE
Question about docs & synchronized methods 

### ISSUE THREAD

**Issue by nebis-software** [ashtanko/lru_cache_dart#1]
Hi!,
    in the README you mention that:

Thread-safe Operations: Uses synchronized methods to ensure thread safety when accessing and modifying the cache, making it safe for concurrent use.

which are the  synchronized methods ? which synchronization approach are you using?
Thanks

**Comment by ashtanko** [comment]
Hi @nebis-software !

Thank you for your question! I fixed the issue using locks from `synchronized.dart` [package](https://pub.dev/packages/synchronized). It is now thread-safe. Thank you!

**Comment by nebis-software** [comment]
Thanks for the quick fix!
